# Generated by Django 4.2.4 on 2025-03-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=20)),
                ('season', models.CharField(choices=[('monsoon', 'Monsoon'), ('winter', 'Winter'), ('summer', 'Summer')], max_length=20)),
                ('duration', models.CharField(choices=[('one-day', 'One-Day'), ('weekend', 'Weekend')], max_length=20)),
                ('image', models.ImageField(upload_to='trek_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
