# Generated by Django 4.2.4 on 2025-03-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trek'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='latitude',
            field=models.FloatField(default=19.076),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trek',
            name='longitude',
            field=models.FloatField(default=19.076),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trek',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
