# Generated by Django 4.2.4 on 2025-03-13 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_trek_latitude_trek_longitude_alter_trek_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='trek',
            name='longitude',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
