# Generated by Django 4.2.4 on 2025-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_trek_latitude_remove_trek_longitude_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trek',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
