# Generated by Django 4.2.4 on 2025-03-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_booking_trek_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='id',
        ),
        migrations.AddField(
            model_name='trek',
            name='drop_location',
            field=models.CharField(default='Lonavala Railway Station', max_length=255),
        ),
        migrations.AddField(
            model_name='trek',
            name='meals',
            field=models.TextField(default='Breakfast, Lunch, Dinner included'),
        ),
        migrations.AddField(
            model_name='trek',
            name='pickup_location',
            field=models.CharField(default='Nearest Railway Station', max_length=255),
        ),
        migrations.AddField(
            model_name='trek',
            name='trek_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
