# Generated by Django 4.2.4 on 2025-03-14 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_trek_id_trek_drop_location_trek_meals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trek',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.trek'),
            preserve_default=False,
        ),
    ]
